import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from './ThemeContext';

export const metadata: Metadata = {
  title: 'KoinLab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen'>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
